services:

  adminer:
    image: adminer:5.4.1
    ports:
      - "8083:8080"
    networks:
      - task-network

  postgres:
    image: postgres:16-alpine
    container_name: task_db
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-api
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8081}:8081"
    networks:
      - task-network
    depends_on:
      - postgres
    volumes:
      - ./config/application.yml:/app/config/application.yml

volumes:
  postgres_data:

networks:
  task-network:
    driver: bridge